In [13]:
INPUT = """3,5,3,1,4,4,5,5,2,1,4,3,5,1,3,5,3,2,4,3,5,3,1,1,2,1,4,5,3,1,4,5,4,3,3,4,3,1,1,2,2,4,1,1,4,3,4,4,2,4,3,1,5,1,2,3,2,4,4,1,1,1,3,3,5,1,4,5,5,2,5,3,3,1,1,2,3,3,3,1,4,1,5,1,5,3,3,1,5,3,4,3,1,4,1,1,1,2,1,2,3,2,2,4,3,5,5,4,5,3,1,4,4,2,4,4,5,1,5,3,3,5,5,4,4,1,3,2,3,1,2,4,5,3,3,5,4,1,1,5,2,5,1,5,5,4,1,1,1,1,5,3,3,4,4,2,2,1,5,1,1,1,4,4,2,2,2,2,2,5,5,2,4,4,4,1,2,5,4,5,2,5,4,3,1,1,5,4,5,3,2,3,4,1,4,1,1,3,5,1,2,5,1,1,1,5,1,1,4,2,3,4,1,3,3,2,3,1,1,4,4,3,2,1,2,1,4,2,5,4,2,5,3,2,3,3,4,1,3,5,5,1,3,4,5,1,1,3,1,2,1,1,1,1,5,1,1,2,1,4,5,2,1,5,4,2,2,5,5,1,5,1,2,1,5,2,4,3,2,3,1,1,1,2,3,1,4,3,1,2,3,2,1,3,3,2,1,2,5,2"""

In [11]:
# SAMPLE

INPUT = """3,4,3,1,2"""

In [7]:
# Part 1

lanternfish = [int(x) for x in INPUT.split(",")]
day = 1

while day <= 80:
    oldfish = []
    newfish = []
    for fish in lanternfish:
        if fish == 0:
            oldfish.append(6)
            newfish.append(8)
        else:
            oldfish.append(fish - 1)
    lanternfish = oldfish + newfish

    print ("DAY", day, "NUMBER", len(lanternfish))
    day += 1

DAY 1 NUMBER 300
DAY 2 NUMBER 383
DAY 3 NUMBER 434
DAY 4 NUMBER 492
DAY 5 NUMBER 546
DAY 6 NUMBER 600
DAY 7 NUMBER 600
DAY 8 NUMBER 600
DAY 9 NUMBER 683
DAY 10 NUMBER 734
DAY 11 NUMBER 875
DAY 12 NUMBER 980
DAY 13 NUMBER 1092
DAY 14 NUMBER 1146
DAY 15 NUMBER 1200
DAY 16 NUMBER 1283
DAY 17 NUMBER 1334
DAY 18 NUMBER 1558
DAY 19 NUMBER 1714
DAY 20 NUMBER 1967
DAY 21 NUMBER 2126
DAY 22 NUMBER 2292
DAY 23 NUMBER 2429
DAY 24 NUMBER 2534
DAY 25 NUMBER 2841
DAY 26 NUMBER 3048
DAY 27 NUMBER 3525
DAY 28 NUMBER 3840
DAY 29 NUMBER 4259
DAY 30 NUMBER 4555
DAY 31 NUMBER 4826
DAY 32 NUMBER 5270
DAY 33 NUMBER 5582
DAY 34 NUMBER 6366
DAY 35 NUMBER 6888
DAY 36 NUMBER 7784
DAY 37 NUMBER 8395
DAY 38 NUMBER 9085
DAY 39 NUMBER 9825
DAY 40 NUMBER 10408
DAY 41 NUMBER 11636
DAY 42 NUMBER 12470
DAY 43 NUMBER 14150
DAY 44 NUMBER 15283
DAY 45 NUMBER 16869
DAY 46 NUMBER 18220
DAY 47 NUMBER 19493
DAY 48 NUMBER 21461
DAY 49 NUMBER 22878
DAY 50 NUMBER 25786
DAY 51 NUMBER 27753
DAY 52 NUMBER 31019
DAY 53 NUMBER 33503
DAY 54 NUMBER 36362
DAY 55 NUMBER 39681
DAY 56 NUMBER 42371
DAY 57 NUMBER 47247
DAY 58 NUMBER 50631
DAY 59 NUMBER 56805
DAY 60 NUMBER 61256
DAY 61 NUMBER 67381
DAY 62 NUMBER 73184
DAY 63 NUMBER 78733
DAY 64 NUMBER 86928
DAY 65 NUMBER 93002
DAY 66 NUMBER 104052
DAY 67 NUMBER 111887
DAY 68 NUMBER 124186
DAY 69 NUMBER 134440
DAY 70 NUMBER 146114
DAY 71 NUMBER 160112
DAY 72 NUMBER 171735
DAY 73 NUMBER 190980
DAY 74 NUMBER 204889
DAY 75 NUMBER 228238
DAY 76 NUMBER 246327
DAY 77 NUMBER 270300
DAY 78 NUMBER 294552
DAY 79 NUMBER 317849
DAY 80 NUMBER 351092

In [14]:
# Part 2

from collections import defaultdict

lanternfish = [int(x) for x in INPUT.split(",")]
day = 1

fish_counts = defaultdict(int)
for fish in lanternfish:
    fish_counts[fish] += 1

while day <= 256:
    new_fish_counts = defaultdict(int)
    new_fish_counts[6] = fish_counts[0]
    new_fish_counts[8] = fish_counts[0]
    for i in range(1,9):
        new_fish_counts[i-1] += fish_counts[i]

    fish_counts = new_fish_counts
    print ("DAY", day, "NUMBER", sum(fish_counts.values()))
    day += 1

DAY 1 NUMBER 300
DAY 2 NUMBER 383
DAY 3 NUMBER 434
DAY 4 NUMBER 492
DAY 5 NUMBER 546
DAY 6 NUMBER 600
DAY 7 NUMBER 600
DAY 8 NUMBER 600
DAY 9 NUMBER 683
DAY 10 NUMBER 734
DAY 11 NUMBER 875
DAY 12 NUMBER 980
DAY 13 NUMBER 1092
DAY 14 NUMBER 1146
DAY 15 NUMBER 1200
DAY 16 NUMBER 1283
DAY 17 NUMBER 1334
DAY 18 NUMBER 1558
DAY 19 NUMBER 1714
DAY 20 NUMBER 1967
DAY 21 NUMBER 2126
DAY 22 NUMBER 2292
DAY 23 NUMBER 2429
DAY 24 NUMBER 2534
DAY 25 NUMBER 2841
DAY 26 NUMBER 3048
DAY 27 NUMBER 3525
DAY 28 NUMBER 3840
DAY 29 NUMBER 4259
DAY 30 NUMBER 4555
DAY 31 NUMBER 4826
DAY 32 NUMBER 5270
DAY 33 NUMBER 5582
DAY 34 NUMBER 6366
DAY 35 NUMBER 6888
DAY 36 NUMBER 7784
DAY 37 NUMBER 8395
DAY 38 NUMBER 9085
DAY 39 NUMBER 9825
DAY 40 NUMBER 10408
DAY 41 NUMBER 11636
DAY 42 NUMBER 12470
DAY 43 NUMBER 14150
DAY 44 NUMBER 15283
DAY 45 NUMBER 16869
DAY 46 NUMBER 18220
DAY 47 NUMBER 19493
DAY 48 NUMBER 21461
DAY 49 NUMBER 22878
DAY 50 NUMBER 25786
DAY 51 NUMBER 27753
DAY 52 NUMBER 31019
DAY 53 NUMBER 33503
DAY 54 NUMBER 36362
DAY 55 NUMBER 39681
DAY 56 NUMBER 42371
DAY 57 NUMBER 47247
DAY 58 NUMBER 50631
DAY 59 NUMBER 56805
DAY 60 NUMBER 61256
DAY 61 NUMBER 67381
DAY 62 NUMBER 73184
DAY 63 NUMBER 78733
DAY 64 NUMBER 86928
DAY 65 NUMBER 93002
DAY 66 NUMBER 104052
DAY 67 NUMBER 111887
DAY 68 NUMBER 124186
DAY 69 NUMBER 134440
DAY 70 NUMBER 146114
DAY 71 NUMBER 160112
DAY 72 NUMBER 171735
DAY 73 NUMBER 190980
DAY 74 NUMBER 204889
DAY 75 NUMBER 228238
DAY 76 NUMBER 246327
DAY 77 NUMBER 270300
DAY 78 NUMBER 294552
DAY 79 NUMBER 317849
DAY 80 NUMBER 351092
DAY 81 NUMBER 376624
DAY 82 NUMBER 419218
DAY 83 NUMBER 451216
DAY 84 NUMBER 498538
DAY 85 NUMBER 540879
DAY 86 NUMBER 588149
DAY 87 NUMBER 645644
DAY 88 NUMBER 694473
DAY 89 NUMBER 770310
DAY 90 NUMBER 827840
DAY 91 NUMBER 917756
DAY 92 NUMBER 992095
DAY 93 NUMBER 1086687
DAY 94 NUMBER 1186523
DAY 95 NUMBER 1282622
DAY 96 NUMBER 1415954
DAY 97 NUMBER 1522313
DAY 98 NUMBER 1688066
DAY 99 NUMBER 1819935
DAY 100 NUMBER 2004443
DAY 101 NUMBER 2178618
DAY 102 NUMBER 2369309
DAY 103 NUMBER 2602477
DAY 104 NUMBER 2804935
DAY 105 NUMBER 3104020
DAY 106 NUMBER 3342248
DAY 107 NUMBER 3692509
DAY 108 NUMBER 3998553
DAY 109 NUMBER 4373752
DAY 110 NUMBER 4781095
DAY 111 NUMBER 5174244
DAY 112 NUMBER 5706497
DAY 113 NUMBER 6147183
DAY 114 NUMBER 6796529
DAY 115 NUMBER 7340801
DAY 116 NUMBER 8066261
DAY 117 NUMBER 8779648
DAY 118 NUMBER 9547996
DAY 119 NUMBER 10487592
DAY 120 NUMBER 11321427
DAY 121 NUMBER 12503026
DAY 122 NUMBER 13487984
DAY 123 NUMBER 14862790
DAY 124 NUMBER 16120449
DAY 125 NUMBER 17614257
DAY 126 NUMBER 19267240
DAY 127 NUMBER 20869423
DAY 128 NUMBER 22990618
DAY 129 NUMBER 24809411
DAY 130 NUMBER 27365816
DAY 131 NUMBER 29608433
DAY 132 NUMBER 32477047
DAY 133 NUMBER 35387689
DAY 134 NUMBER 38483680
DAY 135 NUMBER 42257858
DAY 136 NUMBER 45678834
DAY 137 NUMBER 50356434
DAY 138 NUMBER 54417844
DAY 139 NUMBER 59842863
DAY 140 NUMBER 64996122
DAY 141 NUMBER 70960727
DAY 142 NUMBER 77645547
DAY 143 NUMBER 84162514
DAY 144 NUMBER 92614292
DAY 145 NUMBER 100096678
DAY 146 NUMBER 110199297
DAY 147 NUMBER 119413966
DAY 148 NUMBER 130803590
DAY 149 NUMBER 142641669
DAY 150 NUMBER 155123241
DAY 151 NUMBER 170259839
DAY 152 NUMBER 184259192
DAY 153 NUMBER 202813589
DAY 154 NUMBER 219510644
DAY 155 NUMBER 241002887
DAY 156 NUMBER 262055635
DAY 157 NUMBER 285926831
DAY 158 NUMBER 312901508
DAY 159 NUMBER 339382433
DAY 160 NUMBER 373073428
DAY 161 NUMBER 403769836
DAY 162 NUMBER 443816476
DAY 163 NUMBER 481566279
DAY 164 NUMBER 526929718
DAY 165 NUMBER 574957143
DAY 166 NUMBER 625309264
DAY 167 NUMBER 685974936
DAY 168 NUMBER 743152269
DAY 169 NUMBER 816889904
DAY 170 NUMBER 885336115
DAY 171 NUMBER 970746194
DAY 172 NUMBER 1056523422
DAY 173 NUMBER 1152238982
DAY 174 NUMBER 1260932079
DAY 175 NUMBER 1368461533
DAY 176 NUMBER 1502864840
DAY 177 NUMBER 1628488384
DAY 178 NUMBER 1787636098
DAY 179 NUMBER 1941859537
DAY 180 NUMBER 2122985176
DAY 181 NUMBER 2317455501
DAY 182 NUMBER 2520700515
DAY 183 NUMBER 2763796919
DAY 184 NUMBER 2996949917
DAY 185 NUMBER 3290500938
DAY 186 NUMBER 3570347921
DAY 187 NUMBER 3910621274
DAY 188 NUMBER 4259315038
DAY 189 NUMBER 4643685691
DAY 190 NUMBER 5081252420
DAY 191 NUMBER 5517650432
DAY 192 NUMBER 6054297857
DAY 193 NUMBER 6567297838
DAY 194 NUMBER 7201122212
DAY 195 NUMBER 7829662959
DAY 196 NUMBER 8554306965
DAY 197 NUMBER 9340567458
DAY 198 NUMBER 10161336123
DAY 199 NUMBER 11135550277
DAY 200 NUMBER 12084948270
DAY 201 NUMBER 13255420069
DAY 202 NUMBER 14396960797
DAY 203 NUMBER 15755429177
DAY 204 NUMBER 17170230417
DAY 205 NUMBER 18715643088
DAY 206 NUMBER 20476117735
DAY 207 NUMBER 22246284393
DAY 208 NUMBER 24390970346
DAY 209 NUMBER 26481909067
DAY 210 NUMBER 29010849246
DAY 211 NUMBER 31567191214
DAY 212 NUMBER 34471072265
DAY 213 NUMBER 37646348152
DAY 214 NUMBER 40961927481
DAY 215 NUMBER 44867088081
DAY 216 NUMBER 48728193460
DAY 217 NUMBER 53401819592
DAY 218 NUMBER 58049100281
DAY 219 NUMBER 63481921511
DAY 220 NUMBER 69213539366
DAY 221 NUMBER 75432999746
DAY 222 NUMBER 82513436233
DAY 223 NUMBER 89690120941
DAY 224 NUMBER 98268907673
DAY 225 NUMBER 106777293741
DAY 226 NUMBER 116883741103
DAY 227 NUMBER 127262639647
DAY 228 NUMBER 138914921257
DAY 229 NUMBER 151726975599
DAY 230 NUMBER 165123120687
DAY 231 NUMBER 180782343906
DAY 232 NUMBER 196467414682
DAY 233 NUMBER 215152648776
DAY 234 NUMBER 234039933388
DAY 235 NUMBER 255798662360
DAY 236 NUMBER 278989615246
DAY 237 NUMBER 304038041944
DAY 238 NUMBER 332509319505
DAY 239 NUMBER 361590535369
DAY 240 NUMBER 395934992682
DAY 241 NUMBER 430507348070
DAY 242 NUMBER 470951311136
DAY 243 NUMBER 513029548634
DAY 244 NUMBER 559836704304
DAY 245 NUMBER 611498934751
DAY 246 NUMBER 665628577313
DAY 247 NUMBER 728444312187
DAY 248 NUMBER 792097883439
DAY 249 NUMBER 866886303818
DAY 250 NUMBER 943536896704
DAY 251 NUMBER 1030788015440
DAY 252 NUMBER 1124528483385
DAY 253 NUMBER 1225465281617
DAY 254 NUMBER 1339943246938
DAY 255 NUMBER 1457726460752
DAY 256 NUMBER 1595330616005